name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    name: Jupyter Book (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
        #python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch git submodules (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Install Python dependencies
        run: |
          sudo apt-get install python3-pip graphviz
          pip install -r requirements.txt
          PATH="${PATH}:${HOME}/.local/bin"
      - name: Build Jupyter Book
        run: make book
      - name: add a nojekyll file
        run: touch $GITHUB_WORKSPACE/_build/html/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _build/html # The folder the action should deploy.
          clean: true
          single-commit: true
